"""empty message

Revision ID: eb2904f6d00c
Revises: 
Create Date: 2023-10-14 17:18:15.673431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2904f6d00c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('allDay', sa.Boolean(), nullable=True),
    sa.Column('wheelchair', sa.Boolean(), nullable=True),
    sa.Column('blind', sa.Boolean(), nullable=True),
    sa.Column('nfcForBankCards', sa.Boolean(), nullable=True),
    sa.Column('qrRead', sa.Boolean(), nullable=True),
    sa.Column('supportsUsd', sa.Boolean(), nullable=True),
    sa.Column('supportsChargeRub', sa.Boolean(), nullable=True),
    sa.Column('supportsEur', sa.Boolean(), nullable=True),
    sa.Column('supportsRub', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('offices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('salePointName', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('openHours', sa.JSON(), nullable=True),
    sa.Column('openHoursIndividual', sa.JSON(), nullable=True),
    sa.Column('rko', sa.String(length=255), nullable=True),
    sa.Column('officeType', sa.String(length=255), nullable=True),
    sa.Column('salePointFormat', sa.String(length=255), nullable=True),
    sa.Column('suoAvailability', sa.Boolean(), nullable=True),
    sa.Column('hasRamp', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metroStation', sa.String(length=500), nullable=True),
    sa.Column('myBranch', sa.Boolean(), nullable=True),
    sa.Column('kep', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offices')
    op.drop_table('cities')
    op.drop_table('atms')
    # ### end Alembic commands ###
